const article = [
  {
    name: "Data Structure",
    title: "One of the core concepts of programming.",
    thumbnail: "../public/pic1.jpg",
    content: [
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora, nisi dolorum non, sunt quod impedit blanditiis. Voluptates consequatur consectetur voluptatem eos temporibus dolorem minus placeat animi maiores.
  `,
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora, nisi dolorum non, sunt quod impedit blanditiis. Voluptates consequatur consectetur voluptatem eos temporibus dolorem minus placeat animi maiores.
  `,
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora, nisi dolorum non, sunt quod impedit blanditiis. Voluptates consequatur consectetur voluptatem eos temporibus dolorem minus placeat animi maiores.
  `,
    ],
  },
  {
    name: "OOP",
    title: "Master piece in languages.",
    thumbnail: "../public/pic2.jpg",
    content: [
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora, nisi dolorum non, sunt quod impedit blanditiis. Voluptates consequatur consectetur voluptatem eos temporibus dolorem minus placeat animi maiores.
  `,
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora.
  `,
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit
  `,
    ],
  },
  {
    name: "Database",
    title: "Must required part of website.",
    thumbnail: "../public/pic3.jpg",
    content: [
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora, nisi dolorum non, sunt quod impedit blanditiis. Voluptates consequatur consectetur voluptatem eos temporibus dolorem minus placeat animi maiores.
  `,
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora, nisi dolorum non, sunt quod impedit blanditiis. Voluptates consequatur consectetur voluptatem eos temporibus dolorem minus placeat animi maiores.
  `,
      `Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, ratione. Earum nobis assumenda aspernatur. Adipisci iure blanditiis, officiis alias temporibus velit maxime veniam doloribus delectus minus itaque aliquid commodi explicabo illo rerum autem, cumque expedita molestias nostrum perspiciatis. Modi velit, totam, neque eius quibusdam repellat facere corrupti consequatur accusamus, ratione recusandae eveniet illum dolores. Animi natus deserunt aliquam ullam, ea nisi eveniet aut excepturi quasi voluptate. Reprehenderit expedita illo repudiandae ipsum, ipsa atque qui perspiciatis fugit iusto asperiores totam accusantium nesciunt esse ullam dolorum, nam nisi assumenda quisquam rem. Animi, id sapiente. Voluptatum, omnis odit commodi laboriosam at tempore ea eius harum quod rerum totam deleniti facere architecto, voluptas saepe? Enim, repellendus in delectus, provident inventore suscipit, sapiente ex possimus voluptatem maiores at quas perspiciatis. Eius nisi eveniet ea ex! Autem unde labore enim laborum doloribus non. Culpa tempora dolorem iure. Exercitationem quo facilis modi necessitatibus inventore ipsam minima, repellendus quaerat vitae porro at! Facilis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem vitae dignissimos nemo odit libero id dicta voluptates excepturi molestias? Eveniet sequi possimus beatae fuga sit tempora, nisi dolorum non, sunt quod impedit blanditiis. Voluptates consequatur consectetur voluptatem eos temporibus dolorem minus placeat animi maiores
  `,
    ],
  },
];
export default article;
